---
# This playbook deploys DC/OS

- name: apply common configuration to all nodes
  hosts: all
  serial: 10
  become: true

  roles:
    - common

- name: generate the DC/OS configuration
  hosts: workstations
  serial: 10
  become: true

  roles:
    - workstation

- name: deploy DC/OS
  hosts: [ masters, agents, agents_public]
  serial: 10
  become: true

  roles:
    - node
